### ISSUE TITLE
Unclear about paraphrase annotation `Real Value` slot

### ISSUE THREAD

**Issue by CaoHoangTung** [lexmen318/metaCAT#10]
I have successfully run the tool and annotate my custom data. However, in the `paraphrasing` example file, there is a "real value" field in the slots' detail, and I don't see any description of this, what does it do, where does the value come from.

For example 
![image](https://user-images.githubusercontent.com/22815550/130327667-c9e09ede-29b9-49d5-a02b-6e587577a08b.png)

![image](https://user-images.githubusercontent.com/22815550/130327613-78eaec10-34ba-4506-b08d-54e70ef34d19.png)

**Comment by lexmen318** [comment]
Hi, I'm very happy to hear that you've run the tool successfully.
The "real value" design of the tool has two intentions:
1) to provide the relationship of co-reference. e.g. "the restaurant", "the same day", so the real value will be filled with the name of the restaurant and the determined date.
2) to provide convenience when integrating the tool to real online IT system. e.g. the rating value "over 3.50" can be transferred to a symbolic representation "[3.50, ∞)”，which can be analyzed to DB querying SQL.
The real value should be annotated manually, if necessary. Otherwise you can keep it null string.
Any other or further question, contact me.
Best wishes!

**Comment by CaoHoangTung** [comment]
Thank you for the explanation :100: 
I have 1 more question about the paraphrasing sample file. There is a `batch_slot` field in every utterance annotation. However, as in the sample file, the `batch_slot` value is always {}

**Comment by lexmen318** [comment]
The "batch_slot" is used only when there are several enumerated values for the same slot name.
Especially when the system recommend some choices for the user, e.g. "How about XX hotel and YY hotel?".  So here the "hotel.name" slot has two slot values.
So you can see in most cases, "batch_slot" is unnecessary.

**Comment by CaoHoangTung** [comment]
Thank you, that's what I need :) 

But for the record, if there is such a case, how should I format the `batch_slot` value?

**Comment by lexmen318** [comment]
you can format it like this:
"batch_slot": { "Slot_name": [["slot_value1", xx, xx, ''], ["slot_value2", xx, xx]] }
